# Generated by Django 4.1.3 on 2022-12-07 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_student_project_student_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Github',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Linkedin',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
